#!/usr/bin/env python3

import sys

from settings.config import Banner
from settings.config import error
from settings.config import success
from settings.config import info
from settings.config import warning
from settings.config import version
from settings.parser_flags import flags

from settings.outputfile import Out_Put
#from scan import Scanner

from osi.network.ip4 import IP_Address
from osi.network.arp import arp

class Main():
    def __init__(
            self, 
            osi = None, 
            enumerating = False,
            scan = False,
            verbose = False,
            debugging = False,
            target = None,
            ports = None,
            module = None,
            protocole = None,
            output_file = None,
            interface = None
            ) -> None :
        self.flag = flag
        self.osi = osi
        self.enum = enumerating
        self.scan = scan
        self.verbose = verbose
        self.debug = debugging
        self.target = target
        self.ports = ports
        self.module = module
        self.protocole = protocole
        self.outfile = output_file
        self.iface = interface

    def get_target(self):
        if self.target :
            return self.target
        elif self.iface and not self.target:
            return self.iface
        else :
            return None

if __name__ == "__main__":
    print(Banner)
    info(msg = "Author : RayDen")
    info(msg = "Network Analyser and penetration testing tool\n")
    arg = flags()
